rss:
  - name: "Inquirer"
    url: "https://www.inquirer.net/fullfeed"
  - name: "Rappler"
    url: "https://www.rappler.com/feed"
  - name: "PhilStar - Pang Masa"
    url: "https://www.philstar.com/rss/pang-masa"
  - name: "PhilStar - Pilipino Star Ngayon (Metro)"
    url: "https://www.philstar.com/rss/pilipino-star-ngayon/metro"
  - name: "Interaksyon - Celebrities"
    url: "https://interaksyon.philstar.com/celebrities/feed/"
  - name: "Interaksyon - Hobbies & Interests"
    url: "https://interaksyon.philstar.com/hobbies-interests/feed/"
  - name: "Manila Bulletin"
    url: "https://mb.com.ph/feed/"
  - name: "SunStar"
    url: "https://www.sunstar.com.ph/feed"
