rss:
  - name: "Inquirer"
    url: "https://www.inquirer.net/fullfeed"
  - name: "Rappler"
    url: "https://www.rappler.com/feed"
  - name: "PhilStar"
    url: "https://www.philstar.com/rss"
  - name: "Manila Bulletin"
    url: "https://mb.com.ph/feed/"
  - name: "SunStar"
    url: "https://www.sunstar.com.ph/feed"
  - name: "ABS-CBN News"
    url: "https://news.abs-cbn.com/feed"
